/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package view;

/**
 *
 * @author Joao Henrique
 */
public class Count extends javax.swing.JFrame {

    /**
     * Creates new customizer COUNT: comment Joao
     *
     */
    public Count(int total) {
        initComponents();
        totalPeople.setText("Total People : " + total);
        setSize(600, 220);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public Count() {
        this(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalPeople = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        totalPeople.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalPeople.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPeople.setText("Total People : 0");
        add(totalPeople, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Count");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel totalPeople;
    // End of variables declaration//GEN-END:variables
}
